# -*- coding: utf-8 -*-
"""TimeSheetDimobi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18YcFHKJrvoAjbC3TYheNmEcLDA-JXnqN

1. All Imports
"""

import datetime
import json
from JSONDATA import workers_string

import numpy as np

def count_hours(coeff, days, part_time = 8):
  return coeff * part_time * days

"""2. Get date from the previous month"""

def previous_month(date, day):
  new_month, new_year = (
    date.month-1,
    date.year
  ) if date.month != 1 else (12, date.year-1)
  new_date = date.replace(day=day, month=new_month, year=new_year)
  return new_date

"""3. Calculate working days in the current date"""

def calculate_working_days(month, year, half=1):
  # Calculate working days in the current date
  if half == 1:
    date = datetime.date(year, month, 15)
    prev_date = previous_month(date, 26)
    busy_days = np.busday_count(
      prev_date,
      date
    )
  else:
    busy_days = np.busday_count(
      datetime.date(year, month, 16),
      datetime.date(year, month, 25),
    )
  return busy_days

"""4. Main function"""

def calculate(coeff, month, year, half=1, part_time = 8):
  busy_days = calculate_working_days(month, year, half)
  return count_hours(coeff, busy_days, part_time)

"""5. load data"""

data = json.loads(workers_string)
        
part_time = data['part_time']
departments = data['departments']

month = input("Enter month 1-12: ")
year = input("Enter year 2000-2022: ")
term = input("Enter term 1 for 15th, 2 for 25th: ")

month = int(month)
year = int(year)
half = int(term)

print(f"Month: {month}\tYear: {year}\tHalf: {half}")
      
result = ""
      
for department in departments:
    print(department['name'])
    result += f"{department['name']}\n"
        
    for worker in department['workers']:
        name, time = worker.values()
        hours = calculate(time, month, year, half, part_time=part_time)
          
        print(f"{name}:\t{round(hours, 1)} hours")
        result += f"{name}:\t{round(hours, 1)} hours\n"
          
    print()
    result += "\n"